<?php
function getCopyright($county)
{
	$copyrights = array
			("Hampshire" =>
		"Copyright Hampshire County Council, data provided under
the Ordnance Survey OpenData licence.",
			"West Sussex" =>
"The data in this GeoJSON file has been obtained under licence from the council of West Sussex. The Council's Definitive Map is the authoritative source of the council's rights of way. The details of the public rights of way network contained in the Council's data are for information only, and are an interpretation of the Definitive Map, not the Definitive Map itself, and should not be relied on for determining the position or alignment of any public right of way. For legal purposes, the Council's data does not replace their Definitive Map. And changes may have been made to the Definitive Map that are not included in their data. The Council's data contains Ordnance Survey data © Crown copyright and database right 2012. Attempting to view this data with more detail than 1:10000 may produce an inaccurate rendering of the route of a public right of way. Data is also provided by www.rowmaps.com © www.rowmaps.com copyright and database right 2012. The use of this file is licensed on terms equivalent to the Ordnance Survey OpenData Licence. The preceding attribution statements must be contained in any sub-licences of the Information that you grant, together with a requirement that any further sub-licences do the same. The date of this data is 13th July 2012.",
"Surrey" =>
"The data in this GeoJSON file has been obtained under licence from the council of Surrey. The Council's Definitive Map is the authoritative source of their rights of way. The details of the public rights of way network contained in the Council's data are for information only, and are an interpretation of the Definitive Map, not the Definitive Map itself, and should not be relied on for determining the position or alignment of any public right of way. For legal purposes, the Council's data does not replace their Definitive Map. And changes may have been made to the Definitive Map that are not included in their data. The authority's data contains Ordnance Survey data © Crown copyright and database right 2013. Attempting to view this data with more detail than 1:10000 may produce an inaccurate rendering of the route of a public right of way. Data is also provided by www.rowmaps.com © www.rowmaps.com copyright and database right 2013. The use of this file is licensed on terms equivalent to the Ordnance Survey OpenData Licence. The preceding attribution statements must be contained in any sub-licences of the Information that you grant, together with a requirement that any further sub-licences do the same. The date of this data is 1st August 2013.",
"Wiltshire" =>
"The data in this GeoJSON file has been obtained under licence from the council of Wiltshire. The Council's Definitive Map is the authoritative source of the council's rights of way. The details of the public rights of way network contained in the Council's data are for information only, and are an interpretation of the Definitive Map, not the Definitive Map itself, and should not be relied on for determining the position or alignment of any public right of way. For legal purposes, the Council's data does not replace their Definitive Map. And changes may have been made to the Definitive Map that are not included in their data. The Council's data contains Ordnance Survey data © Crown copyright and database right 2012. Attempting to view this data with more detail than 1:10000 may produce an inaccurate rendering of the route of a public right of way. Data is also provided by www.rowmaps.com © www.rowmaps.com copyright and database right 2012. The use of this file is licensed on terms equivalent to the Ordnance Survey OpenData Licence. The preceding attribution statements must be contained in any sub-licences of the Information that you grant, together with a requirement that any further sub-licences do the same. Although the Council regularly updates their copy of this data, the date of this copy is 4th October 2012."
	);

	return $copyrights[$county];
}
?>
