#!/bin/bash
country=$1

OSMOSIS=/home/nick/errol/osmosis-0.42/bin/osmosis

wget http://download.geofabrik.de/europe/great-britain/${country}-latest.osm.pbf	


${OSMOSIS} --rb file=${country}-latest.osm.pbf --tf reject-relations --tee 15 --tf reject-ways --tf accept-nodes place=city,town,village,suburb,hamlet,locality  --wb file=${country}_place.osm.pbf --tf reject-ways --tf accept-nodes natural=peak --wb file=${country}_peak.osm.pbf --tf reject-ways --tf accept-nodes amenity=pub,restaurant,cafe --wb file=${country}_amenity.osm.pbf --tf reject-ways --tf accept-nodes man_made=mast --wb file=${country}_mast.osm.pbf --tf reject-ways --tf accept-nodes power=tower --wb file=${country}_pylon.osm.pbf --tf reject-ways --tf accept-nodes barrier=stile,gate --wb file=${country}_stilegate.osm.pbf --tf reject-ways --tf accept-nodes tourism=information --wb file=${country}_information.osm.pbf --tf accept-ways highway=path,footway,track,bridleway,cycleway,byway,service,steps,residential,unclassified,tertiary,secondary,primary,trunk,motorway,unclassified_link,tertiary_link,secondary_link,primary_link,trunk_link,motorway_link --used-node --wb file=${country}_highway.osm.pbf --tf accept-ways natural=water,wood,heath,moor --used-node --wb file=${country}_natural.osm.pbf --tf accept-ways landuse=forest,reservoir --used-node --wb file=${country}_forest.osm.pbf --tf accept-ways waterway=* --used-node --wb file=${country}_waterway.osm.pbf --tf accept-ways railway=* --used-node --wb file=${country}_railway.osm.pbf --tf reject-ways --tf accept-nodes railway=station --wb file=${country}_station.osm.pbf --tf accept-ways power=line --used-node --wb file=${country}_powerline.osm.pbf --tf accept-ways barrier=* --used-node --wb file=${country}_barrier.osm.pbf

#${OSMOSIS} --rb file=${country}_railway.osm.pbf outPipe.0=out1 --rb file=${country}_waterway.osm.pbf --merge inPipe.0=out1 outPipe.0=out2 --rb file=${country}_natural.osm.pbf --merge inPipe.0=out2 outPipe.0=out3 --rb file=${country}_highway.osm.pbf --merge inPipe.0=out3 outPipe.0=out4 --rb file=${country}_amenity.osm.pbf --merge inPipe.0=out4 outPipe.0=out5 --rb file=${country}_place.osm.pbf --merge inPipe.0=out5 outPipe.0=out6 --rb file=${country}_peak.osm.pbf --merge inPipe.0=out6 outPipe.0=out7 --rb file=${country}_station.osm.pbf --merge inPipe.0=out7 outPipe.0=out8 --rb file=${country}_forest.osm.pbf --merge inPipe.0=out8 --sort --wx file=- | bzip2 > ${country}_relevant.osm.bz2

${OSMOSIS} --rb file=${country}_railway.osm.pbf outPipe.0=out1 --rb file=${country}_waterway.osm.pbf --merge inPipe.0=out1 outPipe.0=out2 --rb file=${country}_natural.osm.pbf --merge inPipe.0=out2 outPipe.0=out3 --rb file=${country}_highway.osm.pbf --merge inPipe.0=out3 outPipe.0=out4 --rb file=${country}_amenity.osm.pbf --merge inPipe.0=out4 outPipe.0=out5 --rb file=${country}_place.osm.pbf --merge inPipe.0=out5 outPipe.0=out6 --rb file=${country}_peak.osm.pbf --merge inPipe.0=out6 outPipe.0=out7 --rb file=${country}_station.osm.pbf --merge inPipe.0=out7 outPipe.0=out8 --rb file=${country}_forest.osm.pbf --merge inPipe.0=out8 outPipe.0=out9 --rb file=${country}_mast.osm.pbf --merge inPipe.0=out9 outPipe.0=out10 --rb file=${country}_pylon.osm.pbf --merge inPipe.0=out10 outPipe.0=out11 --rb file=${country}_stilegate.osm.pbf --merge inPipe.0=out11 outPipe.0=out12 --rb file=${country}_information.osm.pbf --merge inPipe.0=out12 outPipe.0=out13 --rb file=${country}_powerline.osm.pbf --merge inPipe.0=out13 outPipe.0=out14 --rb file=${country}_barrier.osm.pbf --merge inPipe.0=out14 --sort --wx file=- | bzip2 > ${country}_relevant.osm.bz2

#rm ${country}_place.osm.pbf ${country}_peak.osm.pbf ${country}_amenity.osm.pbf ${country}_highway.osm.pbf ${country}_railway.osm.pbf ${country}_waterway.osm.pbf ${country}_natural.osm.pbf ${country}-latest.osm.pbf ${country}_forest.osm.pbf ${country}_station.osm.pbf ${country}_mast.osm.pbf
