<?php
define('FREEMAP_ROOT','http://www.free-map.org.uk');
define('OTV_ROOT','http://www.opentrailview.org');
define('UPLOADS','/home/www-data/uploads');
define('OTV_UPLOADS','/home/www-data/uploads/otvnew');
define('OTV_GPX_UPLOADS','/home/www-data/uploads/otvnew/gpx');
define('OTV_LIVE_PANOS','/var/www/otvnew/pano');
define('PHOTO_UPLOADS','/home/www-data/uploads/photos');
define('CONTOUR_CACHE','/home/www-data/contourcache');
define('CACHE','/home/www-data/fmapcache');
define('PG_DBNAME','gis2');
define('PG_USER','gis');
define('POPULATE_LOCK','/var/www/fm/POPULATE_LOCK');
define('PHP_LIB_DIR','/var/www/lib');
?>
